export default {
  township: [
    {
      name: "Phaan",
      code: "PAN",
      city_id: 54,
      area_id: 36,
      id: 1742,
    },
    {
      name: "Thantaungkyi",
      code: "TTK",
      city_id: 54,
      area_id: 37,
      id: 1743,
    },
    {
      name: "Hlinebwe",
      code: "HBE",
      city_id: 54,
      area_id: 37,
      id: 1744,
    },
    {
      name: "Pharpon",
      code: "PHR",
      city_id: 54,
      area_id: 37,
      id: 1745,
    },
    {
      name: "HtoneAi",
      code: "HAI",
      city_id: 54,
      area_id: 37,
      id: 1746,
    },
    {
      name: "ZarTaPyin",
      code: "ZTP",
      city_id: 54,
      area_id: 37,
      id: 1747,
    },
    {
      name: "MyineKalay",
      code: "MKL",
      city_id: 54,
      area_id: 37,
      id: 1748,
    },
    {
      name: "Kautkarake",
      code: "KKR",
      city_id: 54,
      area_id: 37,
      id: 1749,
    },
    {
      name: "Kyarinnsatekyi",
      code: "KIS",
      city_id: 54,
      area_id: 37,
      id: 1750,
    },
    {
      name: "Kyonedoe",
      code: "KDO",
      city_id: 54,
      area_id: 37,
      id: 1751,
    },
    {
      name: "Naboo",
      code: "NBO",
      city_id: 54,
      area_id: 37,
      id: 1752,
    },
    {
      name: "Phayartonesu",
      code: "PYTS",
      city_id: 54,
      area_id: 37,
      id: 1753,
    },
    {
      name: "KautBane",
      code: "KBN",
      city_id: 54,
      area_id: 37,
      id: 1754,
    },
    {
      name: "Shanywarthit",
      code: "SYT",
      city_id: 54,
      area_id: 37,
      id: 1755,
    },
    {
      name: "Bawkali",
      code: "BKI",
      city_id: 54,
      area_id: 37,
      id: 1756,
    },
    {
      name: "Myawaady",
      code: "MWD",
      city_id: 54,
      area_id: 37,
      id: 1757,
    },
    {
      name: "Thingan Nyi Nang",
      code: "TNN",
      city_id: 54,
      area_id: 37,
      id: 1758,
    },
    {
      name: "Sukali",
      code: "SKL",
      city_id: 54,
      area_id: 37,
      id: 1759,
    },
    {
      name: "Wawlaymyine",
      code: "WLM",
      city_id: 54,
      area_id: 37,
      id: 1760,
    },
    {
      name: "Thantaungthit",
      code: "TTT",
      city_id: 54,
      area_id: 37,
      id: 1761,
    },
    {
      name: "Kamamaung",
      code: "KMM",
      city_id: 54,
      area_id: 37,
      id: 1762,
    },
    {
      name: "Lateto",
      code: "LTO",
      city_id: 54,
      area_id: 37,
      id: 1763,
    },
    {
      name: "ShweGone",
      code: "SGN",
      city_id: 54,
      area_id: 37,
      id: 1764,
    },
    {
      name: "MyingKyiNgu",
      code: "MGK",
      city_id: 54,
      area_id: 37,
      id: 1765,
    },
    {
      name: "Phalan",
      code: "PHL",
      city_id: 51,
      area_id: 39,
      id: 1766,
    },
    {
      name: "Teetain",
      code: "TET",
      city_id: 51,
      area_id: 39,
      id: 1767,
    },
    {
      name: "Htantalan",
      code: "HTL",
      city_id: 51,
      area_id: 39,
      id: 1768,
    },
    {
      name: "Mintat",
      code: "MIN",
      city_id: 51,
      area_id: 39,
      id: 1769,
    },
    {
      name: "Matupi",
      code: "MTP",
      city_id: 51,
      area_id: 37,
      id: 1770,
    },
    {
      name: "Yaezwar",
      code: "YZR",
      city_id: 51,
      area_id: 37,
      id: 1771,
    },
    {
      name: "TuanZan",
      code: "TUZ",
      city_id: 51,
      area_id: 37,
      id: 1772,
    },
    {
      name: "Harkhar",
      code: "HKR",
      city_id: 51,
      area_id: 37,
      id: 1773,
    },
    {
      name: "KanPatLan",
      code: "KPL",
      city_id: 51,
      area_id: 37,
      id: 1774,
    },
    {
      name: "Yid",
      code: "YID",
      city_id: 51,
      area_id: 37,
      id: 1775,
    },
    {
      name: "LoneBan",
      code: "LNB",
      city_id: 51,
      area_id: 37,
      id: 1776,
    },
    {
      name: "HtokeHlaing",
      code: "HHG",
      city_id: 51,
      area_id: 37,
      id: 1777,
    },
    {
      name: "KatTel",
      code: "KTL",
      city_id: 51,
      area_id: 37,
      id: 1778,
    },
    {
      name: "PelKom",
      code: "PKM",
      city_id: 53,
      area_id: 37,
      id: 1779,
    },
    {
      name: "SharTaw",
      code: "SHT",
      city_id: 53,
      area_id: 37,
      id: 1780,
    },
    {
      name: "PhaRuSo",
      code: "PRS",
      city_id: 53,
      area_id: 37,
      id: 1781,
    },
    {
      name: "DeeMawSo",
      code: "DMS",
      city_id: 53,
      area_id: 33,
      id: 1782,
    },
    {
      name: "PawPiTa",
      code: "PPT",
      city_id: 53,
      area_id: 37,
      id: 1783,
    },
    {
      name: "BawLaKe",
      code: "BLK",
      city_id: 53,
      area_id: 37,
      id: 1784,
    },
    {
      name: "PharSaung",
      code: "PSG",
      city_id: 53,
      area_id: 37,
      id: 1785,
    },
    {
      name: "MawSe",
      code: "MWS",
      city_id: 53,
      area_id: 37,
      id: 1786,
    },
    {
      name: "SharThit",
      code: "STI",
      city_id: 53,
      area_id: 37,
      id: 1787,
    },
    {
      name: "NanMawKhone",
      code: "NKE",
      city_id: 53,
      area_id: 37,
      id: 1788,
    },
    {
      name: "Sagaing",
      code: "SGG",
      city_id: 60,
      area_id: 35,
      id: 1789,
    },
    {
      name: "MyinMu",
      code: "MMU",
      city_id: 60,
      area_id: 35,
      id: 1790,
    },
    {
      name: "Myaung",
      code: "MYN",
      city_id: 60,
      area_id: 36,
      id: 1791,
    },
    {
      name: "YwaThitKyi",
      code: "YTK",
      city_id: 60,
      area_id: 36,
      id: 1792,
    },
    {
      name: "Ywar Htaung",
      code: "YHT",
      city_id: 60,
      area_id: 36,
      id: 1793,
    },
    {
      name: "Sar Htaung",
      code: "STG",
      city_id: 60,
      area_id: 36,
      id: 1794,
    },
    {
      name: "NyaungPinMine",
      code: "NPM",
      city_id: 60,
      area_id: 36,
      id: 1795,
    },
    {
      name: "OonTaw",
      code: "OOT",
      city_id: 60,
      area_id: 36,
      id: 1796,
    },
    {
      name: "KhanPat",
      code: "KPT",
      city_id: 60,
      area_id: 36,
      id: 1797,
    },
    {
      name: "MinTone",
      code: "MTN",
      city_id: 60,
      area_id: 36,
      id: 1798,
    },
    {
      name: "U AungZayYa",
      code: "AZY",
      city_id: 60,
      area_id: 36,
      id: 1799,
    },
    {
      name: "BanDuLa",
      code: "BDL",
      city_id: 60,
      area_id: 36,
      id: 1800,
    },
    {
      name: "HlaTaw",
      code: "HLW",
      city_id: 60,
      area_id: 35,
      id: 1801,
    },
    {
      name: "ShweBo",
      code: "SBO",
      city_id: 60,
      area_id: 35,
      id: 1802,
    },
    {
      name: "KhinOo",
      code: "KOO",
      city_id: 60,
      area_id: 35,
      id: 1803,
    },
    {
      name: "WatLat",
      code: "WLT",
      city_id: 60,
      area_id: 35,
      id: 1804,
    },
    {
      name: "KantBaLu",
      code: "KBL",
      city_id: 60,
      area_id: 35,
      id: 1805,
    },
    {
      name: "DePeYin",
      code: "DPY",
      city_id: 60,
      area_id: 35,
      id: 1806,
    },
    {
      name: "TantSal",
      code: "TTS",
      city_id: 60,
      area_id: 37,
      id: 1807,
    },
    {
      name: "YaeOo",
      code: "YOO",
      city_id: 60,
      area_id: 35,
      id: 1808,
    },
    {
      name: "MoeDar",
      code: "MDR",
      city_id: 60,
      area_id: 36,
      id: 1809,
    },
    {
      name: "InnYwar",
      code: "IYR",
      city_id: 60,
      area_id: 36,
      id: 1810,
    },
    {
      name: "MonYwa",
      code: "MYW",
      city_id: 60,
      area_id: 35,
      id: 1811,
    },
    {
      name: "Butalin",
      code: "BTL",
      city_id: 60,
      area_id: 36,
      id: 1812,
    },
    {
      name: "AyarTaw",
      code: "AYT",
      city_id: 60,
      area_id: 35,
      id: 1813,
    },
    {
      name: "ChaungOo",
      code: "COO",
      city_id: 60,
      area_id: 35,
      id: 1814,
    },
    {
      name: "YinMarPin",
      code: "YMP",
      city_id: 60,
      area_id: 36,
      id: 1815,
    },
    {
      name: "SarLinKyi",
      code: "SLK",
      city_id: 60,
      area_id: 36,
      id: 1816,
    },
    {
      name: "Pale",
      code: "PLE",
      city_id: 60,
      area_id: 36,
      id: 1817,
    },
    {
      name: "Kani",
      code: "KNI",
      city_id: 60,
      area_id: 36,
      id: 1818,
    },
    {
      name: "Namakha",
      code: "NMK",
      city_id: 60,
      area_id: 36,
      id: 1819,
    },
    {
      name: "Alone",
      code: "ALO",
      city_id: 60,
      area_id: 37,
      id: 1820,
    },
    {
      name: "LayShe",
      code: "LSE",
      city_id: 60,
      area_id: 36,
      id: 1821,
    },
    {
      name: "LaManti",
      code: "LMT",
      city_id: 60,
      area_id: 36,
      id: 1822,
    },
    {
      name: "LaHal",
      code: "LHL",
      city_id: 60,
      area_id: 36,
      id: 1823,
    },
    {
      name: "KyunHla",
      code: "KHA",
      city_id: 60,
      area_id: 36,
      id: 1824,
    },
    {
      name: "KyutMyaung(Shwe Bo)",
      code: "KMS",
      city_id: 60,
      area_id: 35,
      id: 1825,
    },
    {
      name: "SateKun",
      code: "SKU",
      city_id: 60,
      area_id: 37,
      id: 1826,
    },
    {
      name: "KarBoe",
      code: "KBE ",
      city_id: 60,
      area_id: 37,
      id: 1827,
    },
    {
      name: "ChatThin",
      code: "CTN",
      city_id: 60,
      area_id: 37,
      id: 1828,
    },
    {
      name: "HtanTaPin(ShweBo)",
      code: "HTA",
      city_id: 60,
      area_id: 35,
      id: 1829,
    },
    {
      name: "MawLu",
      code: "MLU",
      city_id: 60,
      area_id: 37,
      id: 1830,
    },
    {
      name: "NaBar",
      code: "NBR",
      city_id: 60,
      area_id: 37,
      id: 1831,
    },
    {
      name: "MaeZar",
      code: "MZR",
      city_id: 60,
      area_id: 37,
      id: 1832,
    },
    {
      name: "KyaeHmone",
      code: "KHM",
      city_id: 60,
      area_id: 36,
      id: 1833,
    },
    {
      name: "Amyint",
      code: "AMT",
      city_id: 60,
      area_id: 36,
      id: 1834,
    },
    {
      name: "Sitkai",
      code: "SKI",
      city_id: 60,
      area_id: 36,
      id: 1835,
    },
    {
      name: "MinKing",
      code: "MIK",
      city_id: 60,
      area_id: 36,
      id: 1836,
    },
    {
      name: "NatChaung",
      code: "NCG",
      city_id: 60,
      area_id: 36,
      id: 1837,
    },
    {
      name: "MaSein",
      code: "MSN",
      city_id: 60,
      area_id: 36,
      id: 1838,
    },
    {
      name: "KyarPin",
      code: "KPN",
      city_id: 60,
      area_id: 36,
      id: 1839,
    },
    {
      name: "MawLight",
      code: "MLT",
      city_id: 60,
      area_id: 36,
      id: 1840,
    },
    {
      name: "PhaungPin",
      code: "PPN",
      city_id: 60,
      area_id: 36,
      id: 1841,
    },
    {
      name: "KingTat",
      code: "KTT",
      city_id: 60,
      area_id: 36,
      id: 1842,
    },
    {
      name: "MinYar",
      code: "MYR",
      city_id: 60,
      area_id: 36,
      id: 1843,
    },
    {
      name: "KaThar",
      code: "KTR",
      city_id: 60,
      area_id: 37,
      id: 1844,
    },
    {
      name: "KawLin",
      code: "KLN",
      city_id: 60,
      area_id: 37,
      id: 1845,
    },
    {
      name: "HteeChate",
      code: "HCT",
      city_id: 60,
      area_id: 37,
      id: 1846,
    },
    {
      name: "InnTaw",
      code: "ITW",
      city_id: 60,
      area_id: 37,
      id: 1847,
    },
    {
      name: "BaMout",
      code: "BMT",
      city_id: 60,
      area_id: 37,
      id: 1848,
    },
    {
      name: "PinLaeBo",
      code: "PLB",
      city_id: 60,
      area_id: 37,
      id: 1849,
    },
    {
      name: "WoonTo",
      code: "WTO",
      city_id: 60,
      area_id: 37,
      id: 1850,
    },
    {
      name: "NanKhan",
      code: "NKN",
      city_id: 60,
      area_id: 37,
      id: 1851,
    },
    {
      name: "Kalay",
      code: "KLY",
      city_id: 60,
      area_id: 38,
      id: 1852,
    },
    {
      name: "Kalaywa",
      code: "KWA",
      city_id: 60,
      area_id: 39,
      id: 1853,
    },
    {
      name: "KhanTee",
      code: "KHE",
      city_id: 60,
      area_id: 39,
      id: 1854,
    },
    {
      name: "TarHan",
      code: "THN",
      city_id: 60,
      area_id: 39,
      id: 1855,
    },
    {
      name: "Hommalin",
      code: "HML",
      city_id: 60,
      area_id: 39,
      id: 1856,
    },
    {
      name: "NaungPoAung",
      code: "NPA",
      city_id: 60,
      area_id: 39,
      id: 1857,
    },
    {
      name: "TaMuu",
      code: "TMU",
      city_id: 60,
      area_id: 38,
      id: 1858,
    },
    {
      name: "MyoThit",
      code: "MTH",
      city_id: 60,
      area_id: 39,
      id: 1859,
    },
    {
      name: "Pathein",
      code: "PTH",
      city_id: 49,
      area_id: 35,
      id: 1860,
    },
    {
      name: "KanKyiDout",
      code: "KKT",
      city_id: 49,
      area_id: 33,
      id: 1861,
    },
    {
      name: "TharPaung",
      code: "TPG",
      city_id: 49,
      area_id: 34,
      id: 1862,
    },
    {
      name: "NgaPuTaw",
      code: "NPW",
      city_id: 49,
      area_id: 33,
      id: 1863,
    },
    {
      name: "KyonePyaw",
      code: "KPW",
      city_id: 49,
      area_id: 33,
      id: 1864,
    },
    {
      name: "YaeKyi",
      code: "YKI",
      city_id: 49,
      area_id: 33,
      id: 1865,
    },
    {
      name: "KyaungKone",
      code: "KKE",
      city_id: 49,
      area_id: 33,
      id: 1866,
    },
    {
      name: "NgaTineChaung",
      code: "NTC",
      city_id: 49,
      area_id: 33,
      id: 1867,
    },
    {
      name: "ShweTaungYan",
      code: "STY",
      city_id: 49,
      area_id: 33,
      id: 1868,
    },
    {
      name: "NgweSaung",
      code: "NGS",
      city_id: 49,
      area_id: 33,
      id: 1869,
    },
    {
      name: "NgaYoteGaung",
      code: "NYG",
      city_id: 49,
      area_id: 33,
      id: 1870,
    },
    {
      name: "Athote",
      code: "ATE",
      city_id: 49,
      area_id: 33,
      id: 1871,
    },
    {
      name: "DarKa",
      code: "DKA",
      city_id: 49,
      area_id: 36,
      id: 1872,
    },
    {
      name: "MyatTo",
      code: "MTO",
      city_id: 49,
      area_id: 36,
      id: 1873,
    },
    {
      name: "KyikeLat",
      code: "KLT",
      city_id: 49,
      area_id: 33,
      id: 1874,
    },
    {
      name: "Hinttada",
      code: "HTD",
      city_id: 49,
      area_id: 35,
      id: 1875,
    },
    {
      name: "LayMyatHnar",
      code: "LMN",
      city_id: 49,
      area_id: 33,
      id: 1876,
    },
    {
      name: "MyanAung",
      code: "MYA",
      city_id: 49,
      area_id: 33,
      id: 1877,
    },
    {
      name: "KyanKhin",
      code: "KKN",
      city_id: 49,
      area_id: 33,
      id: 1878,
    },
    {
      name: "Inngapu",
      code: "IGP",
      city_id: 49,
      area_id: 33,
      id: 1879,
    },
    {
      name: "Zalon",
      code: "ZLN",
      city_id: 49,
      area_id: 33,
      id: 1880,
    },
    {
      name: "KaNaung",
      code: "KNG",
      city_id: 49,
      area_id: 33,
      id: 1881,
    },
    {
      name: "NgaPiSate(MyanAung)",
      code: "NPS",
      city_id: 49,
      area_id: 36,
      id: 1882,
    },
    {
      name: "InnPin",
      code: "IPN",
      city_id: 49,
      area_id: 36,
      id: 1883,
    },
    {
      name: "Batye",
      code: "BYE",
      city_id: 49,
      area_id: 33,
      id: 1884,
    },
    {
      name: "HtooKyi",
      code: "HTI",
      city_id: 49,
      area_id: 33,
      id: 1885,
    },
    {
      name: "MaeZaLiKone",
      code: "MZL",
      city_id: 49,
      area_id: 33,
      id: 1886,
    },
    {
      name: "DanBi",
      code: "DBI",
      city_id: 49,
      area_id: 36,
      id: 1887,
    },
    {
      name: "KwinKoke",
      code: "KWK",
      city_id: 49,
      area_id: 36,
      id: 1888,
    },
    {
      name: "Naung-Cho",
      code: "NCO",
      city_id: 61,
      area_id: 36,
      id: 1889,
    },
    {
      name: "DoutKyi",
      code: "DKI",
      city_id: 49,
      area_id: 36,
      id: 1890,
    },
    {
      name: "MaUBin",
      code: "MUB",
      city_id: 49,
      area_id: 33,
      id: 1891,
    },
    {
      name: "NyaungTone",
      code: "NTE",
      city_id: 49,
      area_id: 33,
      id: 1892,
    },
    {
      name: "PanTaNaw",
      code: "PTN",
      city_id: 49,
      area_id: 33,
      id: 1893,
    },
    {
      name: "DaNuPhyu",
      code: "DNP",
      city_id: 49,
      area_id: 33,
      id: 1894,
    },
    {
      name: "YaeLeKalay",
      code: "YLK",
      city_id: 49,
      area_id: 36,
      id: 1895,
    },
    {
      name: "ShweTawHmaw",
      code: "STH",
      city_id: 49,
      area_id: 36,
      id: 1896,
    },
    {
      name: "SaKarKyi",
      code: "SKK",
      city_id: 49,
      area_id: 36,
      id: 1897,
    },
    {
      name: "TaungKyi",
      code: "TKY",
      city_id: 49,
      area_id: 36,
      id: 1898,
    },
    {
      name: "Htaung",
      code: "AHG",
      city_id: 49,
      area_id: 33,
      id: 1899,
    },
    {
      name: "ThidaKonePyin",
      code: "TKP",
      city_id: 49,
      area_id: 36,
      id: 1900,
    },
    {
      name: "NgaPiSate(YaeKyi)",
      code: "NPY",
      city_id: 49,
      area_id: 36,
      id: 1901,
    },
    {
      name: "ChaungThar",
      code: "CTR",
      city_id: 49,
      area_id: 36,
      id: 1902,
    },
    {
      name: "PhyarPone",
      code: "PPE",
      city_id: 49,
      area_id: 33,
      id: 1903,
    },
    {
      name: "DayDaYe",
      code: "DDY",
      city_id: 49,
      area_id: 33,
      id: 1904,
    },
    {
      name: "Bokalay",
      code: "BKL",
      city_id: 49,
      area_id: 34,
      id: 1905,
    },
    {
      name: "Lattputthar",
      code: "LPT",
      city_id: 49,
      area_id: 34,
      id: 1906,
    },
    {
      name: "HiKyi",
      code: "HKY",
      city_id: 49,
      area_id: 33,
      id: 1907,
    },
    {
      name: "MawKyun",
      code: "MWK",
      city_id: 49,
      area_id: 34,
      id: 1908,
    },
    {
      name: "PyinSaLu",
      code: "PSL",
      city_id: 49,
      area_id: 33,
      id: 1909,
    },
    {
      name: "ThoneMyineMyoThit",
      code: "TMM",
      city_id: 49,
      area_id: 36,
      id: 1910,
    },
    {
      name: "HlineBone",
      code: "HBN",
      city_id: 49,
      area_id: 36,
      id: 1911,
    },
    {
      name: "KyoneKu",
      code: "KKU",
      city_id: 49,
      area_id: 36,
      id: 1912,
    },
    {
      name: "PyinKhaYine",
      code: "PKY",
      city_id: 49,
      area_id: 36,
      id: 1913,
    },
    {
      name: "MyaungMya",
      code: "MMA",
      city_id: 49,
      area_id: 34,
      id: 1914,
    },
    {
      name: "WarKhalMa",
      code: "WKM",
      city_id: 49,
      area_id: 34,
      id: 1915,
    },
    {
      name: "EainMe",
      code: "EME",
      city_id: 49,
      area_id: 34,
      id: 1916,
    },
    {
      name: "PyinYwar",
      code: "PYR",
      city_id: 49,
      area_id: 36,
      id: 1917,
    },
    {
      name: "KyoneMaNgay",
      code: "KMN",
      city_id: 49,
      area_id: 34,
      id: 1918,
    },
    {
      name: "ShweLaung",
      code: "SLG",
      city_id: 49,
      area_id: 36,
      id: 1919,
    },
    {
      name: "Amar",
      code: "AMR",
      city_id: 49,
      area_id: 34,
      id: 1920,
    },
    {
      name: "KyoneKaDon",
      code: "KKD",
      city_id: 49,
      area_id: 36,
      id: 1921,
    },
    {
      name: "KaDonKaNi",
      code: "KDN",
      city_id: 49,
      area_id: 36,
      id: 1922,
    },
    {
      name: "MyinKaKone",
      code: "MKK",
      city_id: 49,
      area_id: 36,
      id: 1923,
    },
    {
      name: "Bago",
      code: "BGO",
      city_id: 50,
      area_id: 36,
      id: 1924,
    },
    {
      name: "DikeO",
      code: "DIO",
      city_id: 50,
      area_id: 35,
      id: 1925,
    },
    {
      name: "NyaungLayPin",
      code: "NLP",
      city_id: 50,
      area_id: 35,
      id: 1926,
    },
    {
      name: "Kawa",
      code: "KAW",
      city_id: 50,
      area_id: 35,
      id: 1927,
    },
    {
      name: "ShweKyin",
      code: "SKY",
      city_id: 50,
      area_id: 35,
      id: 1928,
    },
    {
      name: "ThaNatPin",
      code: "TNP",
      city_id: 50,
      area_id: 35,
      id: 1929,
    },
    {
      name: "Waw",
      code: "WAW",
      city_id: 50,
      area_id: 35,
      id: 1930,
    },
    {
      name: "OktharMyoThit",
      code: "OTM",
      city_id: 50,
      area_id: 35,
      id: 1931,
    },
    {
      name: "PhaYarKyi",
      code: "PYK",
      city_id: 50,
      area_id: 35,
      id: 1932,
    },
    {
      name: "InnDaKaw",
      code: "IDK",
      city_id: 50,
      area_id: 35,
      id: 1933,
    },
    {
      name: "HtoneKyi",
      code: "HKI",
      city_id: 50,
      area_id: 35,
      id: 1934,
    },
    {
      name: "PyinPoneKyi",
      code: "PPK",
      city_id: 50,
      area_id: 35,
      id: 1935,
    },
    {
      name: "PainZaLote",
      code: "PZL",
      city_id: 50,
      area_id: 35,
      id: 1936,
    },
    {
      name: "PyunTanZar",
      code: "PTZ",
      city_id: 50,
      area_id: 35,
      id: 1937,
    },
    {
      name: "PaeNweKone",
      code: "PKE",
      city_id: 50,
      area_id: 35,
      id: 1938,
    },
    {
      name: "PhaungTawThi",
      code: "PTT",
      city_id: 50,
      area_id: 35,
      id: 1939,
    },
    {
      name: "TatKaLa",
      code: "TKL",
      city_id: 50,
      area_id: 35,
      id: 1940,
    },
    {
      name: "WatHteeKan",
      code: "WTK",
      city_id: 50,
      area_id: 35,
      id: 1941,
    },
    {
      name: "KhittayarMyoThit",
      code: "KMT",
      city_id: 50,
      area_id: 35,
      id: 1942,
    },
    {
      name: "Pyae",
      code: "PAE",
      city_id: 50,
      area_id: 34,
      id: 1943,
    },
    {
      name: "PaungTaLae",
      code: "PTL",
      city_id: 50,
      area_id: 35,
      id: 1944,
    },
    {
      name: "Padekone",
      code: "PDK",
      city_id: 50,
      area_id: 35,
      id: 1945,
    },
    {
      name: "Innma",
      code: "INM",
      city_id: 50,
      area_id: 35,
      id: 1946,
    },
    {
      name: "TaungNgu",
      code: "TGU",
      city_id: 50,
      area_id: 35,
      id: 1947,
    },
    {
      name: "Phyu",
      code: "PYU",
      city_id: 50,
      area_id: 35,
      id: 1948,
    },
    {
      name: "YaeTarShae",
      code: "YTS",
      city_id: 50,
      area_id: 35,
      id: 1949,
    },
    {
      name: "HtanTaPin(Taung Ngu)",
      code: "HTP",
      city_id: 50,
      area_id: 35,
      id: 1950,
    },
    {
      name: "OkeTwin",
      code: "OTW",
      city_id: 50,
      area_id: 35,
      id: 1951,
    },
    {
      name: "KyutKyi",
      code: "KKI",
      city_id: 50,
      area_id: 35,
      id: 1952,
    },
    {
      name: "KaNyutKwin",
      code: "KNK",
      city_id: 50,
      area_id: 35,
      id: 1953,
    },
    {
      name: "KayTuMadi",
      code: "KTM",
      city_id: 50,
      area_id: 35,
      id: 1954,
    },
    {
      name: "ZayyarWaddy",
      code: "ZYW",
      city_id: 50,
      area_id: 35,
      id: 1955,
    },
    {
      name: "Swar",
      code: "SWR",
      city_id: 50,
      area_id: 35,
      id: 1956,
    },
    {
      name: "YaeNi",
      code: "YNI",
      city_id: 50,
      area_id: 35,
      id: 1957,
    },
    {
      name: "MyoHla",
      code: "MYO",
      city_id: 50,
      area_id: 35,
      id: 1958,
    },
    {
      name: "TharGaYa",
      code: "TGY",
      city_id: 50,
      area_id: 35,
      id: 1959,
    },
    {
      name: "Mone",
      code: "MNE",
      city_id: 50,
      area_id: 35,
      id: 1960,
    },
    {
      name: "PaungTal",
      code: "PTA",
      city_id: 50,
      area_id: 35,
      id: 1961,
    },
    {
      name: "PokeKaung",
      code: "PKK",
      city_id: 50,
      area_id: 35,
      id: 1962,
    },
    {
      name: "ThaeKone",
      code: "THK",
      city_id: 50,
      area_id: 35,
      id: 1963,
    },
    {
      name: "ShweTaung",
      code: "STA",
      city_id: 50,
      area_id: 35,
      id: 1964,
    },
    {
      name: "PanTaung",
      code: "PAT",
      city_id: 50,
      area_id: 35,
      id: 1965,
    },
    {
      name: "HtoneBo",
      code: "HBO",
      city_id: 50,
      area_id: 35,
      id: 1966,
    },
    {
      name: "OkShitPin",
      code: "OKP",
      city_id: 50,
      area_id: 35,
      id: 1967,
    },
    {
      name: "Tharyarwaddy",
      code: "TYD",
      city_id: 50,
      area_id: 34,
      id: 1968,
    },
    {
      name: "Latpadan",
      code: "LPD",
      city_id: 50,
      area_id: 35,
      id: 1969,
    },
    {
      name: "OkePho",
      code: "OPH",
      city_id: 50,
      area_id: 35,
      id: 1970,
    },
    {
      name: "Nattalin",
      code: "NTL",
      city_id: 50,
      area_id: 35,
      id: 1971,
    },
    {
      name: "MoeNyo",
      code: "MNO",
      city_id: 50,
      area_id: 35,
      id: 1972,
    },
    {
      name: "KyoPinKaut",
      code: "KPK",
      city_id: 50,
      area_id: 33,
      id: 1973,
    },
    {
      name: "MinHla",
      code: "MLA",
      city_id: 50,
      area_id: 35,
      id: 1974,
    },
    {
      name: "ZeeKone",
      code: "ZEK",
      city_id: 50,
      area_id: 35,
      id: 1975,
    },
    {
      name: "TharYaWaw",
      code: "TYW ",
      city_id: 50,
      area_id: 35,
      id: 1976,
    },
    {
      name: "ZeePhyuKone",
      code: "ZPK",
      city_id: 50,
      area_id: 35,
      id: 1977,
    },
    {
      name: "ThoneSal",
      code: "TSL",
      city_id: 50,
      area_id: 34,
      id: 1978,
    },
    {
      name: "TarPon",
      code: "TPN",
      city_id: 50,
      area_id: 35,
      id: 1979,
    },
    {
      name: "TaungNyo",
      code: "TNO",
      city_id: 50,
      area_id: 35,
      id: 1980,
    },
    {
      name: "AyeMyaTharyar",
      code: "AMY",
      city_id: 50,
      area_id: 35,
      id: 1981,
    },
    {
      name: "SinHmeeSwe",
      code: "SHS",
      city_id: 50,
      area_id: 35,
      id: 1982,
    },
    {
      name: "SinTe",
      code: "STE",
      city_id: 50,
      area_id: 35,
      id: 1983,
    },
    {
      name: "KwinHla",
      code: "KWH",
      city_id: 50,
      area_id: 35,
      id: 1984,
    },
    {
      name: "KyeeTe",
      code: "KYE",
      city_id: 50,
      area_id: 35,
      id: 1985,
    },
    {
      name: "OoThaeKone",
      code: "OTK",
      city_id: 50,
      area_id: 35,
      id: 1986,
    },
    {
      name: "Tharyarwaddy2",
      code: "LMN",
      city_id: 50,
      area_id: 35,
      id: 1987,
    },
    {
      name: "TitKwin",
      code: "TKW",
      city_id: 50,
      area_id: 35,
      id: 1988,
    },
    {
      name: "HteinTaw",
      code: "HTW",
      city_id: 50,
      area_id: 35,
      id: 1989,
    },
    {
      name: "YaeKin",
      code: "YAK",
      city_id: 50,
      area_id: 35,
      id: 1990,
    },
    {
      name: "Dawei",
      code: "DWI",
      city_id: 62,
      area_id: 37,
      id: 1991,
    },
    {
      name: "PaungLone",
      code: "PAL",
      city_id: 62,
      area_id: 37,
      id: 1992,
    },
    {
      name: "ThaYatChaung",
      code: "TYC",
      city_id: 62,
      area_id: 37,
      id: 1993,
    },
    {
      name: "YaePhyu",
      code: "YPU",
      city_id: 62,
      area_id: 37,
      id: 1994,
    },
    {
      name: "HeinNar",
      code: "HNR",
      city_id: 62,
      area_id: 37,
      id: 1995,
    },
    {
      name: "KalainAung",
      code: "KLA",
      city_id: 62,
      area_id: 37,
      id: 1996,
    },
    {
      name: "MaungMaKan",
      code: "MMK",
      city_id: 62,
      area_id: 37,
      id: 1997,
    },
    {
      name: "KanPoke",
      code: "KPE",
      city_id: 62,
      area_id: 37,
      id: 1998,
    },
    {
      name: "NaungZin",
      code: "NGZ",
      city_id: 62,
      area_id: 37,
      id: 1999,
    },
    {
      name: "Pulaw",
      code: "PUL",
      city_id: 62,
      area_id: 37,
      id: 2000,
    },
    {
      name: "Pala",
      code: "PLA",
      city_id: 62,
      area_id: 37,
      id: 2001,
    },
    {
      name: "ShatPone",
      code: "SPE",
      city_id: 62,
      area_id: 37,
      id: 2002,
    },
    {
      name: "PyiKyiMandaing",
      code: "PKM",
      city_id: 62,
      area_id: 37,
      id: 2003,
    },
    {
      name: "Myeik",
      code: "MYK",
      city_id: 62,
      area_id: 37,
      id: 2004,
    },
    {
      name: "KyunSu",
      code: "KSU",
      city_id: 62,
      area_id: 39,
      id: 2005,
    },
    {
      name: "Tanintharyi",
      code: "TNT",
      city_id: 62,
      area_id: 39,
      id: 2006,
    },
    {
      name: "PaLaut",
      code: "PLT",
      city_id: 62,
      area_id: 39,
      id: 2007,
    },
    {
      name: "Kauttaung",
      code: "KTG",
      city_id: 62,
      area_id: 39,
      id: 2008,
    },
    {
      name: "BokePyin",
      code: "BPN",
      city_id: 62,
      area_id: 39,
      id: 2009,
    },
    {
      name: "KhaMoutKyi",
      code: "KMK",
      city_id: 62,
      area_id: 39,
      id: 2010,
    },
    {
      name: "KayaThuyi",
      code: "KTU",
      city_id: 62,
      area_id: 39,
      id: 2011,
    },
    {
      name: "YaeNanChaung",
      code: "YNC",
      city_id: 55,
      area_id: 35,
      id: 2012,
    },
    {
      name: "Choke",
      code: "CHK",
      city_id: 55,
      area_id: 35,
      id: 2013,
    },
    {
      name: "TaungTwinGyi",
      code: "TTI",
      city_id: 55,
      area_id: 35,
      id: 2014,
    },
    {
      name: "MyoThit(Magway)",
      code: "MMW",
      city_id: 55,
      area_id: 34,
      id: 2015,
    },
    {
      name: "Natmaut",
      code: "NMT",
      city_id: 55,
      area_id: 35,
      id: 2016,
    },
    {
      name: "Michaungye",
      code: "MCY",
      city_id: 55,
      area_id: 35,
      id: 2017,
    },
    {
      name: "Magway",
      code: "MGY",
      city_id: 55,
      area_id: 35,
      id: 2018,
    },
    {
      name: "Yanpal(magwaay)",
      code: "YPL",
      city_id: 55,
      area_id: 34,
      id: 2019,
    },
    {
      name: "Myinkone",
      code: "MKE",
      city_id: 55,
      area_id: 35,
      id: 2020,
    },
    {
      name: "Thityarkaut",
      code: "TYK",
      city_id: 55,
      area_id: 35,
      id: 2021,
    },
    {
      name: "Salay",
      code: "SLY",
      city_id: 55,
      area_id: 35,
      id: 2022,
    },
    {
      name: "Gwecho",
      code: "GCO",
      city_id: 55,
      area_id: 35,
      id: 2023,
    },
    {
      name: "Gwepin",
      code: "GPN",
      city_id: 55,
      area_id: 35,
      id: 2024,
    },
    {
      name: "Chaungnat",
      code: "CNT",
      city_id: 55,
      area_id: 35,
      id: 2025,
    },
    {
      name: "Sattwar",
      code: "STR",
      city_id: 55,
      area_id: 35,
      id: 2026,
    },
    {
      name: "Naunghla",
      code: "NHA",
      city_id: 55,
      area_id: 35,
      id: 2027,
    },
    {
      name: "Lathmatkone",
      code: "LMK",
      city_id: 55,
      area_id: 35,
      id: 2028,
    },
    {
      name: "Thatyat",
      code: "TYT",
      city_id: 55,
      area_id: 35,
      id: 2029,
    },
    {
      name: "Minhla-Upper",
      code: "MHA",
      city_id: 55,
      area_id: 35,
      id: 2030,
    },
    {
      name: "Pakokku",
      code: "PKU",
      city_id: 55,
      area_id: 35,
      id: 2031,
    },
    {
      name: "Satephyu",
      code: "SPU",
      city_id: 55,
      area_id: 35,
      id: 2032,
    },
    {
      name: "Yaesakyo",
      code: "YSK",
      city_id: 55,
      area_id: 35,
      id: 2033,
    },
    {
      name: "Pauk",
      code: "PUK",
      city_id: 55,
      area_id: 35,
      id: 2034,
    },
    {
      name: "Myaing",
      code: "MYI",
      city_id: 55,
      area_id: 35,
      id: 2035,
    },
    {
      name: "Myitchae",
      code: "MCE",
      city_id: 55,
      area_id: 35,
      id: 2036,
    },
    {
      name: "Warphi",
      code: "WPI",
      city_id: 55,
      area_id: 35,
      id: 2037,
    },
    {
      name: "Kyaungchaung",
      code: "KCG",
      city_id: 55,
      area_id: 35,
      id: 2038,
    },
    {
      name: "Pakhankyi",
      code: "PKI",
      city_id: 55,
      area_id: 35,
      id: 2039,
    },
    {
      name: "Kyatsukyin",
      code: "KSK",
      city_id: 55,
      area_id: 35,
      id: 2040,
    },
    {
      name: "Myaetaw",
      code: "MYE",
      city_id: 55,
      area_id: 35,
      id: 2041,
    },
    {
      name: "Gantgaw",
      code: "GGW",
      city_id: 55,
      area_id: 35,
      id: 2042,
    },
    {
      name: "Saw",
      code: "SAW",
      city_id: 55,
      area_id: 35,
      id: 2043,
    },
    {
      name: "Hteelin",
      code: "HLN",
      city_id: 55,
      area_id: 35,
      id: 2044,
    },
    {
      name: "Kyaw",
      code: "KYW",
      city_id: 55,
      area_id: 35,
      id: 2045,
    },
    {
      name: "Kanywar",
      code: "KYR",
      city_id: 55,
      area_id: 35,
      id: 2046,
    },
    {
      name: "KyutHtu",
      code: "KHU",
      city_id: 55,
      area_id: 35,
      id: 2047,
    },
    {
      name: "Kyin",
      code: "KYN",
      city_id: 55,
      area_id: 35,
      id: 2048,
    },
    {
      name: "Laungshae",
      code: "LSH",
      city_id: 55,
      area_id: 35,
      id: 2049,
    },
    {
      name: "Mintone",
      code: "MTE",
      city_id: 55,
      area_id: 35,
      id: 2050,
    },
    {
      name: "Kanma",
      code: "KMA",
      city_id: 55,
      area_id: 35,
      id: 2051,
    },
    {
      name: "MinBu",
      code: "MBU",
      city_id: 55,
      area_id: 35,
      id: 2052,
    },
    {
      name: "Salin",
      code: "SLN",
      city_id: 55,
      area_id: 35,
      id: 2053,
    },
    {
      name: "PwintPhyu",
      code: "PPU",
      city_id: 55,
      area_id: 35,
      id: 2054,
    },
    {
      name: "Ngaphae",
      code: "NGP",
      city_id: 55,
      area_id: 35,
      id: 2055,
    },
    {
      name: "Saytotetaya",
      code: "STT",
      city_id: 55,
      area_id: 35,
      id: 2056,
    },
    {
      name: "Sinphyukyun",
      code: "SPK",
      city_id: 55,
      area_id: 35,
      id: 2057,
    },
    {
      name: "Satu",
      code: "SAT",
      city_id: 55,
      area_id: 35,
      id: 2058,
    },
    {
      name: "KoneZaung",
      code: "KZG",
      city_id: 55,
      area_id: 35,
      id: 2059,
    },
    {
      name: "Shotetaw",
      code: "SHW",
      city_id: 55,
      area_id: 35,
      id: 2060,
    },
    {
      name: "Kyaungtawyar",
      code: "KTY",
      city_id: 55,
      area_id: 35,
      id: 2061,
    },
    {
      name: "Laekine",
      code: "LKE",
      city_id: 55,
      area_id: 35,
      id: 2062,
    },
    {
      name: "TaNyaung",
      code: "TNG",
      city_id: 55,
      area_id: 35,
      id: 2063,
    },
    {
      name: "Padan",
      code: "PDN",
      city_id: 55,
      area_id: 35,
      id: 2064,
    },
    {
      name: "Malon",
      code: "MLN",
      city_id: 55,
      area_id: 35,
      id: 2065,
    },
    {
      name: "Kantote",
      code: "KTE",
      city_id: 55,
      area_id: 35,
      id: 2066,
    },
    {
      name: "Koepin",
      code: "KOP",
      city_id: 55,
      area_id: 35,
      id: 2067,
    },
    {
      name: "Kyawswar",
      code: "KWS",
      city_id: 55,
      area_id: 35,
      id: 2068,
    },
    {
      name: "Pyalo",
      code: "PLO",
      city_id: 55,
      area_id: 35,
      id: 2069,
    },
    {
      name: "Lan",
      code: "ALN",
      city_id: 55,
      area_id: 35,
      id: 2070,
    },
    {
      name: "Sinpaungwae",
      code: "SPW",
      city_id: 55,
      area_id: 35,
      id: 2071,
    },
    {
      name: "Ann",
      code: "ANN",
      city_id: 59,
      area_id: 39,
      id: 2072,
    },
    {
      name: "BuuTheTaung",
      code: "BTT",
      city_id: 59,
      area_id: 39,
      id: 2073,
    },
    {
      name: "Maungtaw",
      code: "MTW",
      city_id: 59,
      area_id: 39,
      id: 2074,
    },
    {
      name: "Minpyar",
      code: "MPR",
      city_id: 59,
      area_id: 39,
      id: 2075,
    },
    {
      name: "MyaePone",
      code: "MPE",
      city_id: 59,
      area_id: 39,
      id: 2076,
    },
    {
      name: "Yataetaung",
      code: "YTT",
      city_id: 59,
      area_id: 39,
      id: 2077,
    },
    {
      name: "PonenarKyun",
      code: "PNK",
      city_id: 59,
      area_id: 39,
      id: 2078,
    },
    {
      name: "Pauttaw",
      code: "PTW",
      city_id: 59,
      area_id: 39,
      id: 2079,
    },
    {
      name: "Palatwa",
      code: "PLW",
      city_id: 59,
      area_id: 39,
      id: 2080,
    },
    {
      name: "Sittwe",
      code: "SWE",
      city_id: 59,
      area_id: 37,
      id: 2081,
    },
    {
      name: "Phyu",
      code: "KPU",
      city_id: 59,
      area_id: 37,
      id: 2082,
    },
    {
      name: "ManAung",
      code: "MAG",
      city_id: 59,
      area_id: 37,
      id: 2083,
    },
    {
      name: "PhoneNyoLate",
      code: "PNL",
      city_id: 59,
      area_id: 37,
      id: 2084,
    },
    {
      name: "kyutsarTine",
      code: "KST",
      city_id: 59,
      area_id: 37,
      id: 2085,
    },
    {
      name: "KyinChaung",
      code: "KCN",
      city_id: 59,
      area_id: 37,
      id: 2086,
    },
    {
      name: "TaungPyoWae",
      code: "TPW",
      city_id: 59,
      area_id: 37,
      id: 2087,
    },
    {
      name: "Mingan",
      code: "MGA",
      city_id: 59,
      area_id: 37,
      id: 2088,
    },
    {
      name: "APoutWa",
      code: "APW",
      city_id: 59,
      area_id: 37,
      id: 2089,
    },
    {
      name: "YoeTaYote",
      code: "YTY",
      city_id: 59,
      area_id: 37,
      id: 2090,
    },
    {
      name: "SayTiPyin",
      code: "STP",
      city_id: 59,
      area_id: 37,
      id: 2091,
    },
    {
      name: "YanByae",
      code: "YBE",
      city_id: 59,
      area_id: 37,
      id: 2092,
    },
    {
      name: "ThanTwel",
      code: "TTL",
      city_id: 59,
      area_id: 37,
      id: 2093,
    },
    {
      name: "TaungGoke",
      code: "TGE",
      city_id: 59,
      area_id: 37,
      id: 2094,
    },
    {
      name: "Gwa",
      code: "GWA",
      city_id: 59,
      area_id: 37,
      id: 2095,
    },
    {
      name: "Maei",
      code: "MEI",
      city_id: 59,
      area_id: 37,
      id: 2096,
    },
    {
      name: "Ngapili",
      code: "NPL",
      city_id: 59,
      area_id: 37,
      id: 2097,
    },
    {
      name: "Kyinli",
      code: "KYL",
      city_id: 59,
      area_id: 37,
      id: 2098,
    },
    {
      name: "SatTwar",
      code: "STW",
      city_id: 59,
      area_id: 37,
      id: 2099,
    },
    {
      name: "ZinChaung",
      code: "ZCG",
      city_id: 59,
      area_id: 37,
      id: 2100,
    },
    {
      name: "KyutNiMaw",
      code: "KNM",
      city_id: 59,
      area_id: 37,
      id: 2101,
    },
    {
      name: "TatTaung",
      code: "TTG",
      city_id: 59,
      area_id: 37,
      id: 2102,
    },
    {
      name: "Mawlamyine",
      code: "MLM",
      city_id: 57,
      area_id: 36,
      id: 2103,
    },
    {
      name: "ChaungSone",
      code: "CSE",
      city_id: 57,
      area_id: 36,
      id: 2104,
    },
    {
      name: "Mudone",
      code: "MDE",
      city_id: 57,
      area_id: 36,
      id: 2105,
    },
    {
      name: "Yae",
      code: "YAE",
      city_id: 57,
      area_id: 36,
      id: 2106,
    },
    {
      name: "Thanphyuzayat",
      code: "TPZ",
      city_id: 57,
      area_id: 36,
      id: 2107,
    },
    {
      name: "KyikeMayaw",
      code: "KMW",
      city_id: 57,
      area_id: 36,
      id: 2108,
    },
    {
      name: "Paung",
      code: "PNG",
      city_id: 57,
      area_id: 36,
      id: 2109,
    },
    {
      name: "Htarwalsu",
      code: "HWS",
      city_id: 57,
      area_id: 36,
      id: 2110,
    },
    {
      name: "Dinewinkwin",
      code: "DWK",
      city_id: 57,
      area_id: 36,
      id: 2111,
    },
    {
      name: "Mudon",
      code: "MDN",
      city_id: 57,
      area_id: 36,
      id: 2112,
    },
    {
      name: "MyineTharyar",
      code: "MTY",
      city_id: 57,
      area_id: 36,
      id: 2113,
    },
    {
      name: "Lamine",
      code: "LME",
      city_id: 57,
      area_id: 36,
      id: 2114,
    },
    {
      name: "Khawsar",
      code: "KSR",
      city_id: 57,
      area_id: 36,
      id: 2115,
    },
    {
      name: "Thathone",
      code: "THT",
      city_id: 57,
      area_id: 36,
      id: 2116,
    },
    {
      name: "KyikeHto",
      code: "KHO",
      city_id: 57,
      area_id: 36,
      id: 2117,
    },
    {
      name: "Beelin",
      code: "BLN",
      city_id: 57,
      area_id: 36,
      id: 2118,
    },
    {
      name: "TheinSate",
      code: "TSE",
      city_id: 57,
      area_id: 36,
      id: 2119,
    },
    {
      name: "YineNyein",
      code: "YNN",
      city_id: 57,
      area_id: 36,
      id: 2120,
    },
    {
      name: "ZineKyike",
      code: "ZKE",
      city_id: 57,
      area_id: 36,
      id: 2121,
    },
    {
      name: "Theinzayat",
      code: "TZY",
      city_id: 57,
      area_id: 36,
      id: 2122,
    },
    {
      name: "MoutPalin",
      code: "MPL",
      city_id: 57,
      area_id: 36,
      id: 2123,
    },
    {
      name: "TaungSon",
      code: "TSN",
      city_id: 57,
      area_id: 36,
      id: 2124,
    },
    {
      name: "Motetama",
      code: "MTM",
      city_id: 57,
      area_id: 36,
      id: 2125,
    },
    {
      name: "KyikeKaMe",
      code: "KKM",
      city_id: 57,
      area_id: 36,
      id: 2126,
    },
    {
      name: "Nattaung",
      code: "NTG",
      city_id: 57,
      area_id: 36,
      id: 2127,
    },
    {
      name: "Kasarwat",
      code: "KSW",
      city_id: 57,
      area_id: 36,
      id: 2128,
    },
    {
      name: "Ywarlot",
      code: "YLT",
      city_id: 57,
      area_id: 36,
      id: 2129,
    },
    {
      name: "MyitKyinar",
      code: "MKN",
      city_id: 52,
      area_id: 37,
      id: 2130,
    },
    {
      name: "Tanine",
      code: "TNE",
      city_id: 52,
      area_id: 37,
      id: 2131,
    },
    {
      name: "Winemaw",
      code: "WMW",
      city_id: 52,
      area_id: 37,
      id: 2132,
    },
    {
      name: "Mapakha",
      code: "MPK",
      city_id: 52,
      area_id: 37,
      id: 2133,
    },
    {
      name: "Banmaw",
      code: "BMW",
      city_id: 52,
      area_id: 37,
      id: 2134,
    },
    {
      name: "Shweku",
      code: "SHK",
      city_id: 52,
      area_id: 37,
      id: 2135,
    },
    {
      name: "Moemout",
      code: "MMT",
      city_id: 52,
      area_id: 37,
      id: 2136,
    },
    {
      name: "Manse",
      code: "MAN",
      city_id: 52,
      area_id: 37,
      id: 2137,
    },
    {
      name: "Moenyin",
      code: "MNN",
      city_id: 52,
      area_id: 37,
      id: 2138,
    },
    {
      name: "Moekaung",
      code: "MKG",
      city_id: 52,
      area_id: 37,
      id: 2139,
    },
    {
      name: "PharKhant",
      code: "PKT",
      city_id: 52,
      area_id: 37,
      id: 2140,
    },
    {
      name: "Hopin",
      code: "HPN",
      city_id: 52,
      area_id: 37,
      id: 2141,
    },
    {
      name: "Nantpate",
      code: "NPE",
      city_id: 52,
      area_id: 37,
      id: 2142,
    },
    {
      name: "Sarmaw",
      code: "SMW",
      city_id: 52,
      area_id: 37,
      id: 2143,
    },
    {
      name: "Yinnbaw",
      code: "YBW",
      city_id: 52,
      area_id: 37,
      id: 2144,
    },
    {
      name: "Nanmar",
      code: "NMR",
      city_id: 52,
      area_id: 37,
      id: 2145,
    },
    {
      name: "Mawhan",
      code: "MHN",
      city_id: 52,
      area_id: 37,
      id: 2146,
    },
    {
      name: "PutarO",
      code: "PTO",
      city_id: 52,
      area_id: 37,
      id: 2147,
    },
    {
      name: "Insein",
      code: "ISN",
      city_id: 63,
      area_id: 33,
      id: 2148,
    },
    {
      name: "Aung Ban",
      code: "ABN",
      city_id: 61,
      area_id: 34,
      id: 2149,
    },
    {
      name: "Aye Thar Yar",
      code: "ATY",
      city_id: 61,
      area_id: 33,
      id: 2150,
    },
    {
      name: "He Hoe",
      code: "HEH",
      city_id: 61,
      area_id: 34,
      id: 2151,
    },
    {
      name: "Taunggyi",
      code: "TGI",
      city_id: 61,
      area_id: 33,
      id: 2152,
    },
    {
      name: "Nyaungshwe",
      code: "NYS",
      city_id: 61,
      area_id: 34,
      id: 2153,
    },
    {
      name: "Shwe Nyaung",
      code: "SNY",
      city_id: 61,
      area_id: 33,
      id: 2154,
    },
    {
      name: "Hopong",
      code: "HOP",
      city_id: 61,
      area_id: 35,
      id: 2155,
    },
    {
      name: "Hsihseng",
      code: "HSS",
      city_id: 61,
      area_id: 35,
      id: 2156,
    },
    {
      name: "Kalaw",
      code: "KLW",
      city_id: 61,
      area_id: 34,
      id: 2157,
    },
    {
      name: "Pindaya",
      code: "PDY",
      city_id: 61,
      area_id: 35,
      id: 2158,
    },
    {
      name: "Ywangan",
      code: "YNG",
      city_id: 61,
      area_id: 35,
      id: 2159,
    },
    {
      name: "Lawksawk",
      code: "LKS",
      city_id: 61,
      area_id: 35,
      id: 2160,
    },
    {
      name: "Pinlaung",
      code: "PLG",
      city_id: 61,
      area_id: 35,
      id: 2161,
    },
    {
      name: "Pekon",
      code: "PKN",
      city_id: 61,
      area_id: 35,
      id: 2162,
    },
    {
      name: "Pinlon",
      code: "PLN",
      city_id: 61,
      area_id: 35,
      id: 2163,
    },
    {
      name: "Loilen",
      code: "LOL",
      city_id: 61,
      area_id: 36,
      id: 2164,
    },
    {
      name: "Laihka",
      code: "LAK",
      city_id: 61,
      area_id: 36,
      id: 2165,
    },
    {
      name: "Nansang",
      code: "NSG",
      city_id: 61,
      area_id: 35,
      id: 2166,
    },
    {
      name: "Kunhing",
      code: "KUN",
      city_id: 61,
      area_id: 36,
      id: 2167,
    },
    {
      name: "Langkho",
      code: "LGK",
      city_id: 61,
      area_id: 35,
      id: 2168,
    },
    {
      name: "Mongnai",
      code: "MNI",
      city_id: 61,
      area_id: 35,
      id: 2169,
    },
    {
      name: "Mongpan",
      code: "MPN",
      city_id: 61,
      area_id: 35,
      id: 2170,
    },
    {
      name: "Lashio",
      code: "LSO",
      city_id: 61,
      area_id: 37,
      id: 2171,
    },
    {
      name: "Hseni",
      code: "HNI",
      city_id: 61,
      area_id: 38,
      id: 2172,
    },
    {
      name: "Muse",
      code: "MSE",
      city_id: 61,
      area_id: 38,
      id: 2173,
    },
    {
      name: "Namhkan",
      code: "NHK",
      city_id: 61,
      area_id: 38,
      id: 2174,
    },
    {
      name: "Kutkai",
      code: "KUK",
      city_id: 61,
      area_id: 36,
      id: 2175,
    },
    {
      name: "Kyaukme",
      code: "KME",
      city_id: 61,
      area_id: 38,
      id: 2176,
    },
    {
      name: "Nawnghkio",
      code: "NKO",
      city_id: 61,
      area_id: 38,
      id: 2177,
    },
    {
      name: "Hsipaw",
      code: "HPW",
      city_id: 61,
      area_id: 38,
      id: 2178,
    },
    {
      name: "Mongmit",
      code: "MIT",
      city_id: 61,
      area_id: 38,
      id: 2179,
    },
    {
      name: "Mabein",
      code: "MBN",
      city_id: 61,
      area_id: 38,
      id: 2180,
    },
    {
      name: "Kengtung",
      code: "KYT",
      city_id: 61,
      area_id: 36,
      id: 2181,
    },
    {
      name: "Monghsat",
      code: "MST",
      city_id: 61,
      area_id: 36,
      id: 2182,
    },
    {
      name: "Mongping",
      code: "MPG",
      city_id: 61,
      area_id: 36,
      id: 2183,
    },
    {
      name: "Mongton",
      code: "MGT",
      city_id: 61,
      area_id: 36,
      id: 2184,
    },
    {
      name: "Tachileik",
      code: "TCL",
      city_id: 61,
      area_id: 36,
      id: 2185,
    },
    {
      name: "Monghpyak",
      code: "MPH",
      city_id: 61,
      area_id: 36,
      id: 2186,
    },
    {
      name: "Dakina Thiri",
      code: "DNR",
      city_id: 58,
      area_id: 34,
      id: 2187,
    },
    {
      name: "Za Bu Thi Ri",
      code: "ZBT",
      city_id: 58,
      area_id: 33,
      id: 2188,
    },
    {
      name: "Tatkon",
      code: "TKN",
      city_id: 58,
      area_id: 34,
      id: 2189,
    },
    {
      name: "Det Khi Na Thi Ri ",
      code: "DKT",
      city_id: 58,
      area_id: 34,
      id: 2190,
    },
    {
      name: "Poke Ba Thi Ri",
      code: "PBT",
      city_id: 58,
      area_id: 33,
      id: 2191,
    },
    {
      name: "Pyinmana",
      code: "PMN",
      city_id: 58,
      area_id: 33,
      id: 2192,
    },
    {
      name: "Lewe",
      code: "LWE",
      city_id: 58,
      area_id: 34,
      id: 2193,
    },
    {
      name: "Oke Ta Ra Thi Ri",
      code: "OTR",
      city_id: 58,
      area_id: 33,
      id: 2194,
    },
    {
      name: "Mingaladon",
      code: "MGD",
      city_id: 63,
      area_id: 33,
      id: 2196,
    },
    {
      name: "Hmawbi",
      code: "HBI",
      city_id: 63,
      area_id: 34,
      id: 2197,
    },
    {
      name: "Hlegu",
      code: "HGU",
      city_id: 63,
      area_id: 34,
      id: 2198,
    },
    {
      name: "Taikkyi",
      code: "TKI",
      city_id: 63,
      area_id: 34,
      id: 2199,
    },
    {
      name: "Htantabin",
      code: "HTB",
      city_id: 63,
      area_id: 34,
      id: 2200,
    },
    {
      name: "Shwepyithar",
      code: "SPT",
      city_id: 63,
      area_id: 33,
      id: 2201,
    },
    {
      name: "Hlaingthayar",
      code: "HTY",
      city_id: 63,
      area_id: 33,
      id: 2202,
    },
    {
      name: "Thingangyun",
      code: "TGG",
      city_id: 63,
      area_id: 33,
      id: 2203,
    },
    {
      name: "Yankin",
      code: "YKN",
      city_id: 63,
      area_id: 33,
      id: 2204,
    },
    {
      name: "South Okkalapa",
      code: "SOK",
      city_id: 63,
      area_id: 33,
      id: 2205,
    },
    {
      name: "North Okkalapa",
      code: "NOK",
      city_id: 63,
      area_id: 33,
      id: 2206,
    },
    {
      name: "Thaketa",
      code: "TKT",
      city_id: 63,
      area_id: 33,
      id: 2207,
    },
    {
      name: "Dawbon",
      code: "DBN",
      city_id: 63,
      area_id: 33,
      id: 2208,
    },
    {
      name: "Tamwe",
      code: "TMW",
      city_id: 63,
      area_id: 33,
      id: 2209,
    },
    {
      name: "Pazundaung",
      code: "PZD",
      city_id: 63,
      area_id: 33,
      id: 2210,
    },
    {
      name: "Botahtaung",
      code: "BTH",
      city_id: 63,
      area_id: 33,
      id: 2211,
    },
    {
      name: "Dagon Myothit (South)",
      code: "SDG",
      city_id: 63,
      area_id: 34,
      id: 2212,
    },
    {
      name: "Dagon Myothit (North)",
      code: "NDG",
      city_id: 63,
      area_id: 33,
      id: 2213,
    },
    {
      name: "Dagon Myothit (East)",
      code: "EDG",
      city_id: 63,
      area_id: 34,
      id: 2214,
    },
    {
      name: "Dagon Myothit (Seikkan)",
      code: "SKM",
      city_id: 63,
      area_id: 34,
      id: 2215,
    },
    {
      name: "Mingalar Taung Nyunt",
      code: "MTN",
      city_id: 63,
      area_id: 33,
      id: 2216,
    },
    {
      name: "Thanlyin",
      code: "TLN",
      city_id: 63,
      area_id: 34,
      id: 2217,
    },
    {
      name: "Kyauktan",
      code: "KTN",
      city_id: 63,
      area_id: 34,
      id: 2218,
    },
    {
      name: "Thongwa",
      code: "TGW",
      city_id: 63,
      area_id: 36,
      id: 2219,
    },
    {
      name: "Khayan",
      code: "KHN",
      city_id: 63,
      area_id: 36,
      id: 2220,
    },
    {
      name: "Twantay",
      code: "TTY",
      city_id: 63,
      area_id: 36,
      id: 2221,
    },
    {
      name: "Kawhmu",
      code: "KMU",
      city_id: 63,
      area_id: 35,
      id: 2222,
    },
    {
      name: "Kungyangon",
      code: "KGG",
      city_id: 63,
      area_id: 35,
      id: 2223,
    },
    {
      name: "Dala",
      code: "DLA",
      city_id: 63,
      area_id: 36,
      id: 2224,
    },
    {
      name: "Seikgyikanaungto",
      code: "SKT",
      city_id: 63,
      area_id: 35,
      id: 2225,
    },
    {
      name: "Kyauk Ta Da",
      code: "KTD",
      city_id: 63,
      area_id: 33,
      id: 2226,
    },
    {
      name: "Pabedan",
      code: "PPD",
      city_id: 63,
      area_id: 33,
      id: 2227,
    },
    {
      name: "Lanmadaw",
      code: "LMD",
      city_id: 63,
      area_id: 33,
      id: 2228,
    },
    {
      name: "Latha",
      code: "LTH",
      city_id: 63,
      area_id: 33,
      id: 2229,
    },
    {
      name: "Ahlone",
      code: "ALE",
      city_id: 63,
      area_id: 33,
      id: 2230,
    },
    {
      name: "Kyeemyindaing",
      code: "KMD",
      city_id: 63,
      area_id: 33,
      id: 2231,
    },
    {
      name: "Sanchaung",
      code: "SCN",
      city_id: 63,
      area_id: 33,
      id: 2232,
    },
    {
      name: "Hlaing ",
      code: "HLG",
      city_id: 63,
      area_id: 33,
      id: 2233,
    },
    {
      name: "Kamaryut",
      code: "KMY",
      city_id: 63,
      area_id: 33,
      id: 2234,
    },
    {
      name: "Mayangone",
      code: "MYG",
      city_id: 63,
      area_id: 33,
      id: 2235,
    },
    {
      name: "Dagon",
      code: "DGN",
      city_id: 63,
      area_id: 33,
      id: 2236,
    },
    {
      name: "Bahan",
      code: "BHN",
      city_id: 63,
      area_id: 33,
      id: 2237,
    },
    {
      name: "Seikkan",
      code: "SKN",
      city_id: 63,
      area_id: 33,
      id: 2238,
    },
    {
      name: "AungMyaeTharZan",
      code: "AMZ",
      city_id: 56,
      area_id: 33,
      id: 2239,
    },
    {
      name: "Chanayetharzan",
      code: "CAZ",
      city_id: 56,
      area_id: 33,
      id: 2240,
    },
    {
      name: "Pyigyitagon",
      code: "PGT",
      city_id: 56,
      area_id: 34,
      id: 2243,
    },
    {
      name: "Amarapura",
      code: "AMP",
      city_id: 56,
      area_id: 35,
      id: 2244,
    },
    {
      name: "Patheingyi",
      code: "PTG",
      city_id: 56,
      area_id: 35,
      id: 2245,
    },
    {
      name: "Pyinoolwin",
      code: "POL",
      city_id: 56,
      area_id: 34,
      id: 2246,
    },
    {
      name: "Madaya",
      code: "MDA",
      city_id: 56,
      area_id: 35,
      id: 2247,
    },
    {
      name: "Singu",
      code: "SGU",
      city_id: 56,
      area_id: 35,
      id: 2248,
    },
    {
      name: "Mogoke",
      code: "MOK",
      city_id: 56,
      area_id: 36,
      id: 2249,
    },
    {
      name: "Thabeikkyin",
      code: "TBK",
      city_id: 56,
      area_id: 36,
      id: 2250,
    },
    {
      name: "Kyaukse",
      code: "KSE",
      city_id: 56,
      area_id: 35,
      id: 2251,
    },
    {
      name: "Sintgaing",
      code: "SGI",
      city_id: 56,
      area_id: 35,
      id: 2252,
    },
    {
      name: "Myittha",
      code: "MTA",
      city_id: 56,
      area_id: 35,
      id: 2253,
    },
    {
      name: "Tada-U",
      code: "TDU",
      city_id: 56,
      area_id: 35,
      id: 2254,
    },
    {
      name: "Myingyan",
      code: "MGN",
      city_id: 56,
      area_id: 35,
      id: 2255,
    },
    {
      name: "Taungtha",
      code: "TTA",
      city_id: 56,
      area_id: 37,
      id: 2256,
    },
    {
      name: "Natogyi",
      code: "NHG",
      city_id: 56,
      area_id: 35,
      id: 2257,
    },
    {
      name: "Kyaukpadaung",
      code: "KPD",
      city_id: 56,
      area_id: 35,
      id: 2258,
    },
    {
      name: "Ngazun",
      code: "NZN",
      city_id: 56,
      area_id: 35,
      id: 2259,
    },
    {
      name: "Nyaung-U",
      code: "NYU",
      city_id: 56,
      area_id: 35,
      id: 2260,
    },
    {
      name: "Yamethin",
      code: "YMT",
      city_id: 56,
      area_id: 37,
      id: 2261,
    },
    {
      name: "Meiktila",
      code: "MTL",
      city_id: 56,
      area_id: 35,
      id: 2262,
    },
    {
      name: "Mahlaing",
      code: "MHL",
      city_id: 56,
      area_id: 35,
      id: 2263,
    },
    {
      name: "Thazi",
      code: "TZI",
      city_id: 56,
      area_id: 35,
      id: 2264,
    },
    {
      name: "Wundwin",
      code: "WDN",
      city_id: 56,
      area_id: 37,
      id: 2265,
    },
    {
      name: "Industrial Myothit/ Zone-1/2",
      code: "MTT",
      city_id: 56,
      area_id: 35,
      id: 2266,
    },
    {
      name: "Thae Taw",
      code: "TTW",
      city_id: 56,
      area_id: 37,
      id: 2267,
    },
    {
      name: "Pyaw Bwe",
      code: "PBE",
      city_id: 56,
      area_id: 37,
      id: 2268,
    },
    {
      name: "Bagan",
      code: "BGN",
      city_id: 56,
      area_id: 35,
      id: 2269,
    },
    {
      name: "ChanMyaTharSi",
      code: "CMZ",
      city_id: 56,
      area_id: 33,
      id: 2270,
    },
    {
      name: "PinPhit",
      code: "PPT",
      city_id: 61,
      area_id: 35,
      id: 2271,
    },
    {
      name: "KyautTaLone",
      code: "KTL",
      city_id: 61,
      area_id: 33,
      id: 2272,
    },
    {
      name: "MineShu",
      code: "MNS",
      city_id: 61,
      area_id: 36,
      id: 2273,
    },
    {
      name: "Ywar Thar Kyi",
      code: "YTK",
      city_id: 63,
      area_id: 34,
      id: 2275,
    },
    {
      name: "Moenae",
      code: "MON",
      city_id: 52,
      area_id: 33,
      id: 2276,
    },
    {
      name: "Myoma",
      code: "MYM",
      city_id: 58,
      area_id: 33,
      id: 2277,
    },
    {
      name: "MaharAungMyay",
      code: "MAM",
      city_id: 56,
      area_id: 33,
      id: 2278,
    },
    {
      name: "Shwepoutkan",
      code: "SPK",
      city_id: 63,
      area_id: 33,
      id: 2279,
    },
    {
      name: "Htoukkyunt",
      code: "HK",
      city_id: 63,
      area_id: 34,
      id: 2280,
    },
    {
      name: "Taungthar",
      code: "TT",
      city_id: 61,
      area_id: 36,
      id: 2281,
    },
    {
      name: "Laukkaing",
      code: "LKG",
      city_id: 61,
      area_id: 35,
      id: 2283,
    },
    {
      name: "NantLang",
      code: "NLM",
      city_id: 61,
      area_id: 35,
      id: 2284,
    },
    {
      name: "Loikaw",
      code: "LKW",
      city_id: 53,
      area_id: 33,
      id: 2285,
    },
    {
      name: "Oak-Kan",
      code: "OKK",
      city_id: 63,
      area_id: 35,
      id: 2286,
    },
    {
      name: "Myauk Oo",
      code: "MOO",
      city_id: 59,
      area_id: 37,
      id: 2288,
    },
    {
      name: "Zay Yar Thi Ri",
      code: "ZYT",
      city_id: 58,
      area_id: 33,
      id: 2289,
    },
    {
      name: "Ah Nee Sakhan",
      code: "ASK",
      city_id: 56,
      area_id: 34,
      id: 2290,
    },
    {
      name: "Latpanhla",
      code: "LPH",
      city_id: 56,
      area_id: 35,
      id: 2291,
    },
    {
      name: "Ngathayout",
      code: "NTY",
      city_id: 56,
      area_id: 35,
      id: 2292,
    },
    {
      name: "Tharwutthti",
      code: "TWH",
      city_id: 56,
      area_id: 35,
      id: 2293,
    },
    {
      name: "Popa",
      code: "POP",
      city_id: 56,
      area_id: 35,
      id: 2294,
    },
    {
      name: "Tagaung",
      code: "TGG",
      city_id: 56,
      area_id: 35,
      id: 2295,
    },
    {
      name: "Kyi Taung Kan",
      code: "KTK",
      city_id: 56,
      area_id: 35,
      id: 2296,
    },
    {
      name: "Kume",
      code: "KME",
      city_id: 56,
      area_id: 35,
      id: 2297,
    },
    {
      name: "Wae Laung",
      code: "WLN",
      city_id: 56,
      area_id: 35,
      id: 2298,
    },
    {
      name: "Pyin Si",
      code: "PSI",
      city_id: 56,
      area_id: 35,
      id: 2299,
    },
    {
      name: "Myo Thar",
      code: "MTR",
      city_id: 56,
      area_id: 35,
      id: 2300,
    },
    {
      name: "Thein Gone",
      code: "TGE",
      city_id: 56,
      area_id: 35,
      id: 2301,
    },
    {
      name: "Yay Zin",
      code: "YZN",
      city_id: 56,
      area_id: 35,
      id: 2302,
    },
    {
      name: "MyitNge",
      code: "MGE",
      city_id: 56,
      area_id: 35,
      id: 2303,
    },
    {
      name: "KyaukTaw",
      code: "KUT",
      city_id: 59,
      area_id: 37,
      id: 2304,
    },
    {
      name: "KyaukTaGa",
      code: "KTA",
      city_id: 50,
      area_id: 35,
      id: 2305,
    },
    {
      name: "Hkamti",
      code: "KTI",
      city_id: 60,
      area_id: 39,
      id: 2306,
    },
    {
      name: "KhoLan",
      code: "KHLN",
      city_id: 61,
      area_id: 36,
      id: 2311,
    },
  ],
  city: [
    {
      name: "Ayarwaddy",
      code: "AYY",
      id: 49,
    },
    {
      name: "Bago",
      code: "BGO",
      id: 50,
    },
    {
      name: "Chin",
      code: "CHN",
      id: 51,
    },
    {
      name: "Kachin",
      code: "KCN",
      id: 52,
    },
    {
      name: "Kayar",
      code: "KYR",
      id: 53,
    },
    {
      name: "Kayin",
      code: "KYN",
      id: 54,
    },
    {
      name: "Magway",
      code: "MGW",
      id: 55,
    },
    {
      name: "Mandalay",
      code: "MDY",
      id: 56,
    },
    {
      name: "Mon",
      code: "MON",
      id: 57,
    },
    {
      name: "Naypyitaw",
      code: "NPT",
      id: 58,
    },
    {
      name: "Rakhine",
      code: "RKE",
      id: 59,
    },
    {
      name: "Sagaing",
      code: "SGG",
      id: 60,
    },
    {
      name: "Shan",
      code: "SHN",
      id: 61,
    },
    {
      name: "Tanintharyi",
      code: "TNY",
      id: 62,
    },
    {
      name: "Yangon",
      code: "YGN",
      id: 63,
    },
  ],
};
